### ISSUE TITLE
Incorrect propriety value

### ISSUE THREAD

**Issue by BrugolaOvoidale** [Gamerooni/FO4Patchers#3]
I think the parser get the wrong value from the .txts, like "value x 10", so a height=5.0 becames 50.0 in the esp. In game it translates in NPC "flying" above the ground. I semi-fixed it by replacing "HHSHeight = height" to "HHSHeight = height/10"  (row 189, Program.cs). I don't know if it's a problem in my end but I thought I would let you know.

**Comment by Gamerooni** [comment]
thank you for finding the issue and the fix. I didn't do much testing for this patcher after I went to do other things in skyrim, so I appreciate you looking into this.

Feel free to make a Pull Request for this, it'd probably save me a bit of time.
